name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest
    
    permissions:
      actions: write
      contents: write
      pull-requests: write

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          token: ${{ secrets.SYNC_FORK }}
          owner: taty2010
          base: main
          head: main
          merge_method: merge
          pr_title: Fork Sync
          auto_approve: true
